version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    networks:
      - my-network
  
  order-service:
    build: ./order-service
    ports:
      - "8082:8080"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: orders
    depends_on:
      - mysql-db
      - user-service
    networks:
      - my-network
  
  product-service:
    build: ./product-service
    ports:
      - "8083:8080"
    depends_on:
      - mongo-db
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: orders
    ports:
      - "3307:3306"
    networks:
      - my-network
  
  mongo-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge